### ISSUE TITLE
request for scala.js version

### ISSUE THREAD

**Issue by aappddeevv** [svroonland/rezilience#32]
Against scala.js >= 1.0

**Comment by svroonland** [comment]
@aappddeevv Good one! I'll what I can do but I have zero scalajs experience. Would you like to help?

**Comment by aappddeevv** [comment]
I may be able to help with some config, as I would just copy it from the zio project so its consistently applied.

However, are there underlying dependencies that are beyond zio or the standard scala library? If that's the case, its much more difficult to manage.

**Comment by svroonland** [comment]
I think dependencies should be fine: 

```scala
      "dev.zio"                %%% "zio-streams"             % "1.0.1",
      "dev.zio"                %%% "zio-test"                % "1.0.1" % "test",
      "dev.zio"                %%% "zio-test-sbt"            % "1.0.1" % "test",
      "org.scala-lang.modules" %%% "scala-collection-compat" % "2.2.0"
```

I'll try to follow https://www.scala-js.org/doc/project/cross-build.html and see how far I get

**Comment by aappddeevv** [comment]
Thank you. I think those should be fine. I'd skip trying to do any tests across platforms and such for now just to get a cross-compile. Most likely, the standard zio and zio streams config may be copy and pasteable.

**Comment by svroonland** [comment]
@aappddeevv https://github.com/svroonland/rezilience/pull/33 Seems to cross-compile and test JVM only. What do you think?

**Comment by aappddeevv** [comment]
I'll take a look at it.

**Comment by aappddeevv** [comment]
I think its working but you are potentially assembling everything to the same jar file in bin. You would need to split out the assembly jar name to the individual subprojects (jvm and js settings) or let it default.

Also, you can drop the scalajsMainInitializer line, that's not needed.

The cross project thing creates 2 projects, called rezilienceJVM and rezilienceJS so you can run the commands separately if you want to see what is going on. You can tell if the JS compiler was used because if you unzip list the .jar file it has .sjsir files in it.

You will need to rename those assemblies so that they are scala.js friendly e.g. the assembly should have the name sjs1 scalaVersion type suffix. I'm not 100% sure of the intent behind the jar bin config.

**Comment by svroonland** [comment]
Right. I removed those settings and from the `publishLocal` output it looks like it's now producing separate assemblies with the correct names.

I'm not sure where that jar bin config originated from, it's been copy-pasted too many times.

I'm going to try to publish it.

Thanks!

**Comment by svroonland** [comment]
Alright I believe I succeeded: https://bintray.com/vroste/maven/rezilience/0.3.1#files/nl/vroste

**Comment by aappddeevv** [comment]
I'll give it a try but it does look like it published correctly. Thanks for publishing.
