### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by garraspin** [svroonland/rezilience#362]
Hi, 

First of all thanks for your work. 

I really like the library and I would like to use it. Unfortunately I can't do it if it hasn't got a license.

Will you be adding a license any time soon? Could you consider using Apache v2?

Kind regards,
S.

**Comment by svroonland** [comment]
Absolutely, sorry for the oversight. I'm already using the Apache 2 license for zio-kinesis, I've added it to rezilience as well.

Thanks for the heads up!
