### ISSUE TITLE
The jar for 0.10.2 - scala 2.13 on maven central is empty

### ISSUE THREAD

**Issue by jgordijn** [svroonland/rezilience#439]
```
❯ unzip -t Rezilience\ 2.13\ 0.10.2.jar
Archive:  Rezilience 2.13 0.10.2.jar
    testing: META-INF/MANIFEST.MF     OK
No errors detected in compressed data of Rezilience 2.13 0.10.2.jar.
```

**Comment by svroonland** [comment]
Thanks for reporting. No idea what has gone wrong there, never encountered this issue before. I released 0.10.3 and the jar seems OK again.

https://mvnrepository.com/artifact/nl.vroste/rezilience_2.13/0.10.3
