### ISSUE TITLE
Migrate hosting elsewhere (JCenter closing down)

### ISSUE THREAD

**Issue by virusdave** [svroonland/rezilience#93]
Per [this page](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), it looks like your current artifact hosting location will be shutting down.  Are you planning to move to another location?

**Comment by svroonland** [comment]
Hi @virusdave, thanks for the reminder. I will likely move rezilience to sonatype. Already have credentials set up for it, so it should be an easy switch.

**Comment by svroonland** [comment]
@virusdave Latest version should be available from maven central, as well as snapshots from Sonatype!
